url: "https://www.noesya.coop"
title: "noesya"
baseline: "Coopérative de développeurs"
description: "La coopérative noesya s’engage pour un numérique de grande qualité, éco-conçu, esthétique, éthique et durable."
email: "contact@noesya.coop"
lang: fr

#theme: jekyll-theme-noesya

options:
  menu_burger: true
  notes: true # Needed to use notes in sections-with-notes includes
  paragraphs_index: true # Needed to add index to paragraphs
  hover_navigation_links: true # Needed to use nav-between-pages
  no_js: false

exclude:
  - noesya.gemspec
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"

collections:
  pages:
    output: true

plugins:
  - jekyll-minifier
  - jekyll-sitemap

sass:
  style: compressed
  load_paths:
      - _sass
      - node_modules

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: false
  remove_comments: true
  compress_css: false
  compress_javascript: true

picture:
  ignore_missing_images: true
