url: "https://www.noesya.coop"
title: "noesya"
baseline: "Coopérative de développeurs"
description: "This is a demo content for homepage Noesya Jekyll Theme"
email: "contact@noesya.coop"
lang: fr

#theme: jekyll-theme-noesya

options:
  menu_burger: true # For desktop
  notes: false # Needed to use notes in sections-with-notes includes
  paragraphs_index: false # Needed to add index to paragraphs
  hover_navigation_links: false # Needed to use nav-between-pages
  no_js: false

exclude:
  - noesya.gemspec
  - LICENSE

defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
      nav_auto: true
      
collections:
  pages:
    sort_by: title
    output: true

plugins:
  - jekyll-minifier
  - jekyll-sitemap

sass:
  style: compressed
  load_paths:
      - _sass
      - node_modules

jekyll-minifier:
  remove_spaces_inside_tags: true
  remove_multi_spaces: true
  remove_intertag_spaces: false
  remove_comments: true
  compress_css: false
  compress_javascript: true

picture:
  ignore_missing_images: true
